[package]
name = "comet"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
comet-div = { workspace = true }
comet-layout = { workspace = true }
comet-renderer = { workspace = true }

taffy = "0.9.2"
parley = "0.7.0"
peniko = "0.6.0"
kurbo = "0.13.0"
slotmap = "1.1.1"
color = "0.3.2"
anyrender = "0.7.0"
anyrender_vello = "0.7.1"

[dev-dependencies]
image = "0.25.8"
